name: BukkitRadar
main: denniss17.bukkitRadar.BukkitRadar
version: 1.1.0
author: Denniss17
website: 'http://dev.bukkit.org/server-mods/bukkitradar/'
description: Show a radar
commands:
   bukkitradar:
      description: Set your radar
      aliases: [br, radar]
permissions:
   bukkitradar.bukkitradar:
       description: Permission to use the command
       default: op
   bukkitradar.clearradar:
       description: Permission to clear your radar
       default: true
   bukkitRadar.bigradius:
       description: Allows user to have a bigger radar radius
       default: op
   bukkitradar.playerradar:
       description: Permission to use the player radar
       default: op
       children:
           bukkitradar.bukkitradar: true
           bukkitradar.clearradar: true
   bukkitradar.oreradar:
       description: Permission to use the ore radar
       default: op
       children:
           bukkitradar.bukkitradar: true
           bukkitradar.clearradar: true
   bukkitradar.mobradar:
       description: Permission to use the mob radar
       default: op
       children:
           bukkitradar.bukkitradar: true
           bukkitradar.clearradar: true
   bukkitradar.reload:
       description: Permission to reload the config
       default: op
   bukkitradar.*:
       description: All permissions for this plugin
       default: op
       children:
           bukkitradar.mobradar: true
           bukkitradar.playerradar: true
           bukkitradar.reload: true